# fly.toml app configuration file generated for ai-supabase-compliance on 2025-02-20T00:27:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-supabase-compliance'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
